### PR TITLE
Feature/dockstore work

### PR DESCRIPTION
**Pull request by garyluu**
- Fixes
- Add TRS validator

### CODE REVIEW

**Comment by denis-yuen** [comment]
@garyluu @denis-yuen note to self: what is status of this work?

**Comment by garyluu** [comment]
I think it's mostly done and compatible with an earlier version of TRS.  Will need an update to TRSV once TRS 2.0 is out.

**Comment by denis-yuen** [comment]
Can we just tag this with what v1.x version this is compatible with and merge? 
The current develop looks odd

**Comment by garyluu** [comment]
Should be able to merge.  Just got to figure out which TRS version it is.  Likely the last v1 version

Edit...there's only 1 TRS v1 version?

**Comment by denis-yuen** [comment]
Yeah, looks like.

**Review by denis-yuen — APPROVED** [review]

**Pull request merged**
